// Jason Brito
// 9.15.2018
// The purpose of this component is to handle the upload of an image using the Upload Service.

import {Component, OnInit} from '@angular/core';
import {UploadService} from '../upload.service'; //import to process upload

@Component({
  selector: 'app-upload',
  templateUrl: './upload.component.html',
  styleUrls: ['./upload.component.css']
})
export class UploadComponent implements OnInit {

  constructor(private UploadService: UploadService) {
  }

  ngOnInit() {
  }

  //passes the event to the Upload Service to process upload
  upload(event) {
    this.UploadService.upload(event);
  }

  //returns the data url generated by the Upload Service
  getURL() {
    return this.UploadService.url;
  }
}
